# Generated by Django 4.2.1 on 2023-05-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_study_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
