# Generated by Django 4.2 on 2023-04-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_profile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="streak",
            field=models.SmallIntegerField(default=0),
        ),
    ]
