# Generated by Django 4.2.1 on 2023-05-10 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_profile_last_study_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_study_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
