# Generated by Django 4.1.7 on 2023-03-10 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('definition_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('spelling', models.CharField(max_length=20)),
                ('pronunciation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('meaning_id', models.AutoField(primary_key=True, serialize=False)),
                ('meaning', models.TextField()),
                ('part_of_speech', models.CharField(choices=[('1', 'Noun'), ('2', 'Verb'), ('3', 'Adjective'), ('4', 'Adverb'), ('5', 'Pronoun'), ('6', 'Preposition'), ('7', 'Conjunction'), ('8', 'Interjection')], max_length=1)),
                ('opposite_meaning_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dictionary.meaning')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('example_id', models.AutoField(primary_key=True, serialize=False)),
                ('example', models.TextField()),
                ('definition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.definition')),
            ],
        ),
        migrations.AddField(
            model_name='definition',
            name='meaning_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.meaning'),
        ),
        migrations.AddField(
            model_name='definition',
            name='tag_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.tag'),
        ),
        migrations.AddField(
            model_name='definition',
            name='word_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word'),
        ),
    ]
