# Generated by Django 4.1.7 on 2023-03-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='part_of_speech',
            field=models.CharField(choices=[('1', 'Danh từ'), ('2', 'Động từ'), ('3', 'Tính từ'), ('4', 'Trạng từ'), ('5', 'Đại từ'), ('6', 'Giới từ'), ('7', 'Liên từ'), ('8', 'Thán từ')], max_length=1),
        ),
    ]
