# Generated by Django 4.1.7 on 2023-03-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_meaning_part_of_speech'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meaning',
            old_name='opposite_meaning_id',
            new_name='opposite_meaning',
        ),
    ]
