# Generated by Django 4.1.7 on 2023-03-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_rename_opposite_meaning_id_meaning_opposite_meaning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definition',
            old_name='meaning_id',
            new_name='meaning',
        ),
        migrations.RenameField(
            model_name='definition',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='definition',
            old_name='word_id',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='example',
            old_name='definition_id',
            new_name='definition',
        ),
    ]
