# Generated by Django 4.1.7 on 2023-03-10 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_rename_meaning_id_definition_meaning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.tag'),
        ),
    ]
