# Generated by Django 4.1.7 on 2023-03-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_alter_definition_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='part_of_speech',
            field=models.CharField(choices=[('1', 'Noun'), ('2', 'Verb'), ('3', 'Adjective'), ('4', 'Adverb'), ('5', 'Pronoun'), ('6', 'Preposition'), ('7', 'Conjunction'), ('8', 'Interjection')], max_length=1),
        ),
    ]
