# Generated by Django 4.2 on 2023-04-20 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0007_searchhistory_remove_example_definition_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SearchHistory",
        ),
    ]
