# Generated by Django 4.1.7 on 2023-03-23 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('privacy', models.SmallIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Word_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('uuid', models.CharField(max_length=50)),
                ('sn', models.CharField(max_length=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.package')),
            ],
        ),
        migrations.CreateModel(
            name='User_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.SmallIntegerField()),
                ('star', models.SmallIntegerField(choices=[(0, 'Not started'), (1, 'Remembered'), (2, 'Understood'), (3, 'Applying')], default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
