# Generated by Django 4.2 on 2023-04-20 07:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "workspace",
            "0002_word_remove_word_package_sn_remove_word_package_uuid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word_package",
            name="package",
        ),
        migrations.RemoveField(
            model_name="word_package",
            name="word",
        ),
        migrations.RemoveField(
            model_name="word",
            name="sn",
        ),
        migrations.RemoveField(
            model_name="word",
            name="uuid",
        ),
        migrations.AddField(
            model_name="package",
            name="progress",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="package",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workspace.package",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name="User_Package",
        ),
        migrations.DeleteModel(
            name="Word_Package",
        ),
    ]
