# Generated by Django 4.2 on 2023-04-20 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "workspace",
            "0003_remove_word_package_package_remove_word_package_word_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="package",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="workspace.package",
            ),
        ),
    ]
