# Generated by Django 4.2 on 2023-04-20 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0004_alter_package_user_alter_word_package"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="word",
            new_name="spelling",
        ),
        migrations.AddField(
            model_name="package",
            name="level",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Not started"),
                    (1, "Remembered"),
                    (2, "Understood"),
                    (3, "Applying"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="progress",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
