# Generated by Django 4.2 on 2023-04-20 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0005_rename_word_word_spelling_package_level_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="spelling",
            new_name="word",
        ),
    ]
