# Generated by Django 4.2 on 2023-04-20 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0006_rename_spelling_word_word"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="word",
            new_name="spelling",
        ),
    ]
