# Generated by Django 4.2 on 2023-04-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0007_rename_word_word_spelling"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="date",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
