# Generated by Django 4.2 on 2023-04-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0010_remove_package_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="note",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
