# Generated by Django 4.2 on 2023-05-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0011_word_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
