# Generated by Django 4.2 on 2023-05-05 07:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0012_alter_word_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="note",
        ),
    ]
